import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Tirthabrata Dutta</title>
        <meta name="description" content="Generated by"></meta>
      </Head>
      <main className="bg-gray-200 px-10 px-10 m:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-burtons'>DANKB01</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className=" font-burtons bg-cyan-500 text-white px-5 py-2 rounded-md ml-8" href="">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Tirthabrata Dutta</h2>
            <h3 className='text-2xl py-2'>DevOps Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl mx-auto'>Software Engineer, working at Ingram Micro in the Cloud Department with hands-on experience in Azure and AWS. Professional and multilingual, certified with multiple cloud certificates as well as experienced in Office 365 products.
I have worked on cloud architecture with customer experience as the priority. Hard working and meticulous, constantly striving to learn new and interesting technologies. I am proven in my ability to provide consistent customer satisfaction and learn different architectures as per necessity.
</p>
          </div>
          <div className='text-5xl flex justify-center text-gray-600'>
            <AiFillLinkedin/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden flex">
            <Image src={deved} layout="fill" objectFit="cover"  />
          </div>
        </section>
      </main>

    </div>
   
  );
}
